### ISSUE TITLE
chrome extension doesnt work with http

### ISSUE THREAD

**Issue by sivasfdc** [Krisa/Salesforce-Workbench#1]
The previous versions of this extension used to work with salesforce.com/force.com domains over plain http.

After the recent update on April 18,2017, the extension stopped working with http and works only with https.

Please add the http URL support in the manifest.json as follows

```
$ diff Salesforce-Workbench-master/manifest.json Salesforce-Workbench-master.modified/manifest.json
17c17
<     "tabs", "https://*.salesforce.com/*", "https://*.force.com/*"
---
>     "tabs", "https://*.salesforce.com/*", "https://*.force.com/*", "http://*.salesforce.com/*", "http://*.force.com/*"
23c23,25
<         "https://*.force.com/*"
---
>         "https://*.force.com/*",
>         "http://*.salesforce.com/*",
>         "http://*.force.com/*"
```

**Comment by 0cv** [comment]
That's true that it doesn't work anymore, but why would you want to use a non-secured version of salesforce.com or force.com? Is that even possible to connect to salesforce from a http url? Going for example to http://login.salesforce.com redirects automatically to https.

**Comment by sivasfdc** [comment]
Thanks for the quick response Chris.

I work with Salesforce and this will be very useful in my internal development environments.

**Comment by 0cv** [comment]
Well, I can add back the http, but I'm still wondering how you can be logged in Salesforce with a http url? Are you connecting to the servers from within the Salesforce network (hence https is not required)?

**Comment by sivasfdc** [comment]
Yes - As i mentioned this for internal dev environment where i can run the Server on my desktop where i use plain http.

**Comment by 0cv** [comment]
Thanks for the explanation, that's interesting... 

The extension is updated, you shall get the update within the next hour.

**Comment by sivasfdc** [comment]
You are lightning fast!!! I will validate the same locally and update this issue.

**Comment by sivasfdc** [comment]
The extension has been updated and it works as expected.

Thank u again for quick response and updates!
