### ISSUE TITLE
"/lightning/switcher?destination=" URL is broken

### ISSUE THREAD

**Issue by sivasfdc** [Krisa/Salesforce-Workbench#3]
background.js uses the following url "/lightning/switcher?destination=" to switch between classic and lex.

That URL is no longer working.

The new URL is "/ltng/switcher?destination"

For classic:
/ltng/switcher?destination=classic
For Lightning:
/ltng/switcher?destination=lex

Please update the background.js accordingly and release a new version to chrome store asap.

**Comment by 0cv** [comment]
Thanks @sivasfdc, it's been re-published and shall be available in the coming hours
