### ISSUE TITLE
No icon in address bar

### ISSUE THREAD

**Issue by GeekyCopadoDeveloper** [Krisa/Salesforce-Workbench#6]
Not able to make it work.
![image](https://user-images.githubusercontent.com/67841529/91031746-a501fe00-e61e-11ea-894c-3583203775b3.png)

**Comment by 0cv** [comment]
@GeekyCopadoDeveloper you cannot use it over `developerforce.com`, they have some restrictions or whatsoever. You will need to install the workbench on your local machine, as detailed here https://github.com/forceworkbench/forceworkbench/wiki#installation
